from .a1111 import A1111
from .easydiffusion import EasyDiffusion
from .invokeai import InvokeAI
from .novelai import NovelAI
from .comfyui import ComfyUI
from .drawthings import DrawThings
from .swarmui import SwarmUI
from .fooocus import Fooocus
from .primere import Primere
